/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20 } from "./Erc20";
export type { UniswapInterfaceMulticall } from "./UniswapInterfaceMulticall";

export { Erc20__factory } from "./factories/Erc20__factory";
export { UniswapInterfaceMulticall__factory } from "./factories/UniswapInterfaceMulticall__factory";
